# Fetches Spotify information

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

import yt_dlp

SETTINGS_FILE_LOCATION = ""
NUM_ACCEPTED_SEARCHES = 5

keys: list[str] = None
market: str = None

def update_settings():
    try:
        file = open(SETTINGS_FILE_LOCATION, "r")
        keys.clear()
        keys.append(file.readline())
        keys.append(file.readline())
        market = file.readline()
        file.close()
    except IOError as e:
        print(e)

def set_spotify_api_keys(client_id: str, client_secret: str):
    try:
        file = open(SETTINGS_FILE_LOCATION, "w")
        file.writelines(f"{client_id}\n", f"{client_secret}\n", f"{market}")
        file.close()
    except IOError as e:
        print(e)

def get_spotify_playlist_tracks(id: str) -> list[dict]:
    sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=keys[0], client_secret=keys[1]))
    return sp.playlist_tracks(playlist_id=id, market=market)["items"]

def search_youtube(title: str, artists: str) -> str:
    # Search for the top few videos---searching with "{Title} {1st artist}"
    # e.g. "née-nah 21 Savage"
    ydl_opts: dict = {
        "ignoreerrors": True
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info: dict = ydl.extract_info(url=f"ytsearch{NUM_ACCEPTED_SEARCHES}:{title} {artists}", download=False)
    search_results: list[dict] = info["entries"]
    # Find the ID of the highest-scoring video
    index: int = 0
    largest_score: int = -9999999
    id_with_largest_score: str = ""
    for search_result in search_results:
        if search_result is None:
            index = index + 1
            continue
        score: int = calculate_video_score(search_result, index, title, artists)
        if score > largest_score:
            largest_score = score
            id_with_largest_score = search_result["id"]
    # Return
    return f"https://www.youtube.com/watch?v={id_with_largest_score}"

def send_tracks_to_java(id: str):
    tracks_java_data: list[dict] = [] # Data we will send over to our Java program
    tracks: list[dict] = get_spotify_playlist_tracks(id)
    artists: str = None
    for track in tracks:
        artists = ""
        for artist_data in track["track"]["artists"]:
            artists = artists + artist_data["name"] + ", "
        artists = artists[:-2]
        tracks_java_data.append({
            "title": track["track"]["name"],
            "artists": artists,
            "album": track["track"]["album"]["name"],
            "artworkURL": track["track"]["album"]["images"][0]["url"],
            "youtubeID": search_youtube(track["track"]["name"], track["track"]["artists"][0]["name"])
        })
    return tracks_java_data
    # TODO: Send tracks_java_data over to the Java program

# How well a video's info matches up with the target track information.
def calculate_video_score(search_result: dict, index: int, target_title: str, target_artists: str) -> int:
    video_title: str = search_result["title"].lower()
    video_channel: str = search_result["channel"].lower()
    video_desc: str = search_result["description"].lower()
    target_title = target_title.lower()
    target_artists = target_artists.lower()
    score: int = 0

    if target_title not in video_title:
        score = score - 2
    
    if target_artists in video_title:
        score = score + 1
    
    if "hour" in video_title or "loop" in video_title or "edit" in video_title or "live" in video_title or "reverb" in video_title or "sped-up" in video_title or "sped up" in video_title or "slowed" in video_title or "remix" in video_title or "cover" in video_title or "mtv" in video_title:
        score = score - 3
    
    if "audio" in video_title or "lyrics" in video_title:
        score = score + 2
    
    if index == 0:
        score = score + 2
    
    if index != 0 and index < 3:
        score = score + 1
    
    if target_artists in video_channel:
        score = score + 1
    
    if "auto-generated by youtube" in video_desc:
        score = score + 2

    return score

if __name__ == "__main__":
    keys = ["1c41bf31426e46a6a4c44d3f9bac1424", "bb9d381f22204bdabbf0418767ca3aaf"]
    market = "US"
    # tracks = None
    # tracks = get_spotify_playlist_tracks("https://open.spotify.com/playlist/1zUUwGZh02drh2M13yNcVD?si=fe3a24a9e483426b")
    # print(tracks)
    # print("\n")
    # print(type(tracks))
    # print(type(tracks[0]))

    # tracks_java_data = send_tracks_to_java("https://open.spotify.com/playlist/1zUUwGZh02drh2M13yNcVD?si=fe3a24a9e483426b")
    # for data in tracks_java_data:
    #     print(data["title"])
    #     print(data["artists"])
    #     print(data["album"])
    #     print(data["artworkURL"])
    #     print(data["youtubeID"])
    #     print()
    
    print(send_tracks_to_java("https://open.spotify.com/playlist/1MBIdnT23Xujh3iHDAURfB?si=c3ad19f5390b4aa1"))

    pass
